/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize the FHE accelerate library
 *
 * This function performs one-time initialization including:
 * - Hardware capability detection (SME, Metal, NEON, AMX)
 * - Memory pool setup for unified memory
 * - Shader compilation for Metal backend
 */
export declare function initialize(): void
/** Get hardware capabilities available on this system */
export interface HardwareCapabilities {
  hasSme: boolean
  hasMetal: boolean
  hasNeon: boolean
  hasAmx: boolean
  metalGpuCores: number
  unifiedMemorySize: number
}
/** Detect available hardware capabilities */
export declare function detectHardware(): HardwareCapabilities
/** Version information */
export declare function version(): string
/** Modular arithmetic engine */
export declare class ModularArithmetic {
  /** Create a new modular arithmetic engine with the given modulus */
  constructor(modulus: number)
  /** Montgomery multiplication: (a * b * R^-1) mod q */
  montgomeryMul(a: number, b: number): number
  /** Modular addition: (a + b) mod q */
  modAdd(a: number, b: number): number
  /** Modular subtraction: (a - b) mod q */
  modSub(a: number, b: number): number
  /** Convert to Montgomery form: a * R mod q */
  toMontgomery(a: number): number
  /** Convert from Montgomery form: a * R^-1 mod q */
  fromMontgomery(a: number): number
  /** Get the modulus */
  getModulus(): number
}
